### ISSUE TITLE
Trait with default methods

### ISSUE THREAD

**Issue by Olicek** [Symplify/ControllerAutowire#10]
What do you think about trait with methods from `Symfony\Bundle\FrameworkBundle\Controller\Controller`? It can be preatty dificult for new users replace `$this->render('default/index.html.twig');` for `$this->template->renderResponse('default/index.html.twig');`. Also if you want use this extension in the middle of project, you simply can't because you call render method everywhere and it's falls.

For example, in Controller is method `render` which contents `return $this->container->get('templating')->renderResponse($view, $parameters, $response);`

This trait could inject templating (`EngineInterface`) via calls.

```
calls:
    - [setTemplating, ['@templating']]
```

and in trait

```
protected function render($view, array $parameters = array(), Response $response = null)
{
    if (!is_null($this->templating)) {
        return $this->templating->renderResponse($view, $parameters, $response);
    }

    // ...
}
```

Even don't know if it is possible do it in trait, but it maybe can be possible in some abstract Controller with i would can replace Symfony Controller. Is it possible?

**Comment by Olicek** [comment]
ping @TomasVotruba

**Comment by TomasVotruba** [comment]
Thanks for pinging, I lost it somewhere. This might be actually a good idea. 

I saw similar try in Symfony core. I found few files on recherche:

- https://github.com/derrabus/symfony/blob/master-controller-trait/src/Symfony/Bundle/FrameworkBundle/Templating/RenderHelperTrait.php
- https://github.com/symfony/symfony/pull/16863
- https://github.com/symfony/symfony/pull/18193

Traits should be ok then. Could you send PR with few smaller traits?

**Comment by Olicek** [comment]
Yes, i will try it.

**Comment by Olicek** [comment]
I moved it here https://github.com/Symplify/Symplify/issues/14

**Comment by TomasVotruba** [comment]
Thanks
