### ISSUE TITLE
Autowire-ing parameters from container

### ISSUE THREAD

**Issue by PWalkow** [Symplify/ControllerAutowire#5]
Standard way of injecting of the parameters from container is (yaml version):
```
services:
    acme.app.controller.default:
        class: Acme\Bundle\AppBundle\Controller\DefaultController
        arguments: ['%%kernel.root_dir%%','@templating']
```

Controller __construct implementation:

    /**
     * @param string          $kernelRootDir
     * @param EngineInterface $templating
     */
    public function __construct($kernelRootDir, EngineInterface $templating)
    {
        $this->kernelRootDir = $kernelRootDir;
        $this->templating = $templating;
    }

Unfortunately after I have added this bundle in AppKernel I see:

> [Symfony\Component\DependencyInjection\Exception\RuntimeException]
>   Unable to autowire argument index 0 ($kernelRootDir) for the service "acme.bundle.appbundle.controller.defaultcontroller". If this is an object, give it a type-hint. Otherwise, specify this argument's value explicitly.

which do not tell how actually I should accomplish injecting container parameter into it.
Could you please explain how to do it?

**Comment by TomasVotruba** [comment]
Thank for reporting the issue!
Are you able to send failing test? In such a way it would be easier for me to fix it.

**Comment by TomasVotruba** [comment]
Ping @PWalkow

**Comment by PWalkow** [comment]
@TomasVotruba Actually standard symfony installation with AppBundle is enough.

Create new project with symfony standard that has AppBundle inside.
Then 'composer require symplify/controller-autowire', and add this bundle in AppKernel.
Change AppBundle/Controller/DefaultController to:
```php
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
use Symfony\Component\HttpFoundation\Request;

class DefaultController
{
    private $kernelRootDir;
    private $templating;

    public function __construct($kernelRootDir, EngineInterface $templating)
    {
         $this->kernelRootDir = $kernelRootDir;
         $this->templating = $templating;
    }

    /**
     * @Route("/", name="homepage")
     */
    public function indexAction(Request $request)
    {
        // replace this example code with whatever you need
        return $this->templating->renderResponse('default/index.html.twig', [
            'base_dir' => realpath($this->kernelRootDir.'/..'),
        ]);
    }
}
```
run  bin/console and see the error about injecting parameter from container.

**Comment by TomasVotruba** [comment]
I see. This cannot be autowired, since it's not a service.
You have to do this manually.

I'd create a ParmameterProvider service that would wrap parameters.

---

Do you mean this bundle overrides your default service registration?

**Comment by TomasVotruba** [comment]
Any updates here?

**Comment by PWalkow** [comment]
`symfony new test` (with the symfony installer)
`composer require symplify/controller-autowire`
add `new Symplify\ControllerAutowire\SymplifyControllerAutowireBundle(),` inside of the app/AppKernel.php
override `app/config/services.yml` with the code that I have provided in comment on 8 Jun
override `src/AppBundle/Controller/DefaultController.php` with the code that I have provided in comment on 19 Jul

run `bin/console` to see an error.

I hope this will help you to reproduce the error.

**Comment by TomasVotruba** [comment]
Please read my answer, where I explain this is not in range of this bundle: https://github.com/Symplify/ControllerAutowire/issues/5#issuecomment-233766904

**Comment by TomasVotruba** [comment]
I've added test and it works fine.

**Comment by Olicek** [comment]
@PWalkow i tested it with some parameterProvider and it works properly. You can't inject parameters directly. But, to be honest, it's bad practice...
Some snippet here:

```
services:
    parameterProvider:
        class: AppBundle\ParameterProvider
        arguments:
            - %kernel.root_dir%
```

```
class ParameterProvider
{

    private $parameters = [];

    public function __construct($rootDir)
    {
        $this->parameters['rootDir'] = $rootDir;
    }

    public function getRootDir()
    {
        return $this->parameters['rootDir'];
    }

}
```

```
public function __construct(EngineInterface $template, ParameterProvider $parameterProvider)
{
    $this->template = $template;
    $this->parameterProvider = $parameterProvider;
}

public function indexAction()
{
    dump($this->parameterProvider->getRootDir());
}
```

**Comment by TomasVotruba** [comment]
@PWalkow Thank for testing out!
