### ISSUE TITLE
Without using @Route

### ISSUE THREAD

**Issue by J7mbo** [Symplify/ControllerAutowire#6]
Any way to use this without using `@Route` annotations? Would be great if there was...

**Comment by TomasVotruba** [comment]
Hi, I'm not sure I understand the issue. Could describe it a bit more?
I use this without @Route annotations with no problem.

**Comment by J7mbo** [comment]
Sorry, tutorials don't show otherwise so I assumed annotation was the only way!

**Comment by TomasVotruba** [comment]
So everything works?

**Comment by J7mbo** [comment]
Routing-wise, yes, cheers @TomasVotruba.
