### ISSUE TITLE
Autowiring Controller Methods

### ISSUE THREAD

**Issue by J7mbo** [Symplify/ControllerAutowire#7]
I have a controller registered as a service:

    my_controller:
        class: AppBundle\Application\Controller\MyController
        autowire: true

I have the following method signature:

    public function indexAction(\Twig_Environment $templateEngine)

I get the following error:

> Controller "AppBundle\Application\Controller\MyController::indexAction()" requires that you provide a value for the "$templateEngine" argument (because there is no default value or because there is a non optional argument after this one).

**Comment by J7mbo** [comment]
Also perhaps I've misunderstood the use for this library - I thought I could use it to autowire controller methods with it :-)

**Comment by TomasVotruba** [comment]
This bundle:

- finds controllers
- registers them as a services
- autowires controllers

Not it's methods.

**Comment by TomasVotruba** [comment]
Controllers autowire is in Laravel, isn't it?

If you want, I think you can easily create bundle for that.

**Comment by J7mbo** [comment]
Laravel is one of many different frameworks that provide controller method autowiring out of the box. The functionality should be exactly the same for autowiring controllers themselves, except instead of the constructor being targeted the method being called has the reflection / 'container retrieval' functionality as well.

I saw the `DunglasActionBundle` but frankly it is massively over-complicated; the goal is to not have any additional configuration - it should all use the existing dependency injection stuff. Just a thought :-)

**Comment by TomasVotruba** [comment]
I understand the feature. I consider it bad practice, as it complicated constructor injection paradigma. I try to keep it simple as possible to make it most durable in time.

Do you want to help to create your own bundle?

**Comment by J7mbo** [comment]
With a controller with 5 of 6 methods, each requiring different objects, I consider passing every object to the constructor when it is only needed by one method inefficient and bad practice.

I am interested in working on this, we could work on it together, but I'm busy right now building something else (and playing with autowiring :P) - but when it comes to it and I have some free time I'll send you a message and maybe we can collude together!

I'll close this issue as it seems like something that won't be added to this particular project.

**Comment by TomasVotruba** [comment]
In such a case I'd split to more controllers classes. Same goes for any other huge class.

I'd be happy to guide the process. Thanks to this package I got some clues where to start :).

Cheers @J7mbo !

**Comment by TomasVotruba** [comment]
Hey @J7mbo, I got good news :)
A friend of mine came with similar issue so we've decided to create a bundle for that:
https://github.com/Symplify/ActionAutowire

**Comment by J7mbo** [comment]
Hey @TomasVotruba, this looks very promising, and thanks very much for messaging me in here. I'll definitely take a look at this tomorrow.

**Comment by TomasVotruba** [comment]
Glad to help! Hope you like it :) feel free to submit any issues or suggestion to improve.
